apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example3
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    repoURL: "https://github.com/creedasaurus/homelab.git"
    path: apps/services/media/example3
    targetRevision: main
  destination:
    namespace: media
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
