apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  source:
    repoURL: 'https://github.com/creedasaurus/homelab.git'
    path: apps/services/media/example
    targetRevision: main
  destination:
    namespace: media
    name: in-cluster
  syncOptions:
    - CreateNamespace=true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
