apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert
spec:
  secretName: example-tls
  dnsNames:
    - "vulf.haus"
    - "*.vulf.haus"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
