apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-test
spec:
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
    - secretKey: MY_VALUE_1
      remoteRef:
        key: my-test-config
        property: MY_VALUE_1
    - secretKey: MY_VALUE_2
      remoteRef:
        key: my-test-config
        property: MY_VALUE_2
