apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: traefik-external

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`example.vulf.haus`)
      kind: Rule
      services:
        - name: example-guestbook-ui
          port: 80

  tls:
    secretName: cm-shared-wildcard-vulfhaus-tls
