apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yml
helmCharts:
  - name: intel-device-plugins-gpu
    repo: https://intel.github.io/helm-charts
    version: "0.29.0"
    releaseName: intel
    namespace: inteldeviceplugins-system
    includeCRDs: true
    valuesFile: values.yml
