apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
  namespace: database
spec:
  data:
  - remoteRef:
      key: cloudnative-pg
      property: POSTGRES_SUPER_USER
    secretKey: username
  - remoteRef:
      key: cloudnative-pg
      property: POSTGRES_SUPER_PASS
    secretKey: password
  - remoteRef:
      key: vulfminio
      property: MINIO_ROOT_USER
    secretKey: aws-access-key-id
  - remoteRef:
      key: vulfminio
      property: MINIO_ROOT_PASSWORD
    secretKey: aws-secret-access-key
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-connect
  target:
    name: cloudnative-pg-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
