apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres
  namespace: database
spec:
  backupOwnerReference: self
  cluster:
    name: postgres16
  immediate: true
  schedule: '@every 3h'
