apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: infra
  destination:
    namespace: argocd
    name: in-cluster
  source:
    repoURL: "https://github.com/creedasaurus/homelab.git"
    targetRevision: main
    path: apps/infra/argocd
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
