apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: infra
  destination:
    namespace: authentik
    name: in-cluster
  source:
    repoURL: "https://github.com/creedasaurus/homelab.git"
    path: apps/infra/authentik
    targetRevision: main

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
