apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: externalsecrets
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: infra
  destination:
    namespace: external-secrets
    name: in-cluster
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: "0.9.13"
    chart: external-secrets
    helm:
      releaseName: external-secrets
      valuesObject:
        installCRDs: true
    # - repoURL: "https://github.com/creedasaurus/homelab.git"
    #   targetRevision: main
    #   path: apps/infra/longhorn
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
