apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-plugin
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: infra
  destination:
    namespace: inteldeviceplugins-system
    name: in-cluster
  source:
    repoURL: "https://github.com/creedasaurus/homelab.git"
    path: apps/infra/intel
    targetRevision: main

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
