apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: infra
  destination:
    namespace: longhorn-system
    name: in-cluster
  sources:
    - repoURL: https://charts.longhorn.io
      targetRevision: v1.6.0
      chart: longhorn
      helm:
        valuesObject:
          longhornUI:
            replicas: 1
          persistence:
            defaultClassReplicaCount: 1
          defaultSettings:
            defaultReplicaCount: 1
          preUpgradeChecker:
            jobEnabled: false
    - repoURL: "https://github.com/creedasaurus/homelab.git"
      targetRevision: main
      path: apps/infra/longhorn
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
