apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-extra
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    namespace: longhorn-system
    name: in-cluster
  source:
    repoURL: "https://github.com/creedasaurus/homelab.git"
    path: apps/infra/longhorn
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
