apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    namespace: longhorn-system
    name: in-cluster
  sources:
    - repoURL: https://charts.longhorn.io
      targetRevision: v1.6.0
      chart: longhorn
      helm:
        valuesObject:
          defaultSettings:
            defaultReplicaCount: 1
    - repoURL: "https://github.com/creedasaurus/homelab.git"
      targetRevision: main
      path: apps/infra/longhorn
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
