apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: infra
  destination:
    namespace: argocd
    name: in-cluster
  sources:
    - repoURL: "https://github.com/creedasaurus/homelab.git"
      targetRevision: main
      path: apps/infra/minio-operator
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
