apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feature-discovery
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: infra
  destination:
    namespace: node-feature-discovery
    name: in-cluster
  source:
    repoURL: https://kubernetes-sigs.github.io/node-feature-discovery/charts
    targetRevision: "v0.15.4"
    chart: node-feature-discovery
    helm:
      releaseName: nfd
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
