apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: feature-discovery
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: infra
  destination:
    namespace: node-feature-discovery
    name: in-cluster
  sources:
    - repoURL: "https://github.com/creedasaurus/homelab.git"
      targetRevision: main
      path: apps/infra/nfd
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
