# IMPORTANT NOTE: configuration requires knowledge of node cri
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    namespace: gpu-operator
    server: in-cluster
  source:
    chart: gpu-operator
    repoURL: https://helm.ngc.nvidia.com/nvidia
    targetRevision: v23.9.2
    helm:
      valuesObject:
        driver:
          enabled: "false"
        toolkit:
          env:
            - name: CONTAINERD_CONFIG
              value: /var/lib/rancher/k3s/agent/etc/containerd/config.toml
            - name: CONTAINERD_SOCKET
              value: /run/k3s/containerd/containerd.sock
            - name: CONTAINERD_RUNTIME_CLASS
              value: nvidia
            - name: CONTAINERD_SET_AS_DEFAULT
              value: "false"

  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
