apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    namespace: gpu-operator
    name: in-cluster
  source:
    chart: gpu-operator
    repoURL: https://helm.ngc.nvidia.com/nvidia
    targetRevision: v23.9.2
    helm:
      values: |
        driver:
          enabled: "false"
        toolkit:
          enabled: "false"
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
