apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: infra
  destination:
    namespace: openebs
    name: in-cluster
  sources:
    - repoURL: https://openebs.github.io/openebs
      targetRevision: "4.0.1"
      chart: openebs
      helm:
        values: |
          mayastor:
            enabled: true
          engines:
            replicated:
              mayastor:
                enabled: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
