apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: infra
  destination:
    namespace: openebs
    name: in-cluster
  sources:
    - repoURL: https://openebs.github.io/charts
      targetRevision: "3.10.0"
      chart: openebs
      helm:
        values: |
          zfs-localpv:
            enabled: true
          nfs-provisioner:
            enabled: true
            nfsServerNodeAffinity: "kubernetes.io/storage-node,kubernetes.io/nfs-node"
    - repoURL: "https://github.com/creedasaurus/homelab.git"
      targetRevision: main
      path: apps/infra/openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
