apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-7"
spec:
  project: infra
  destination:
    namespace: rook-ceph
    name: in-cluster
  sources:
    - repoURL: "https://github.com/creedasaurus/homelab.git"
      targetRevision: main
      path: apps/infra/rook-ceph
  syncPolicy:
    automated:
      prune: false
