---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio
spec:
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  target:
    name: minio-secret
    template:
      engineVersion: v2
      data:
        config.env: |-
          export MINIO_ROOT_USER={{ .MINIO_ROOT_USER }}
          export MINIO_ROOT_PASSWORD={{ .MINIO_ROOT_PASSWORD }}
  data:
    - secretKey: MINIO_ROOT_USER
      remoteRef:
        key: vulfminio
        property: MINIO_ROOT_USER

    - secretKey: MINIO_ROOT_PASSWORD
      remoteRef:
        key: vulfminio
        property: MINIO_ROOT_PASSWORD
