---
- name: Ping
  ansible.builtin.ping:

- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
      - neovim
      - qemu-guest-agent
      - intel-gpu-tools
      - nfs-common
      - zfsutils-linux
      - open-iscsi
      - lsscsi
      - sg3-utils
      - multipath-tools
      - scsitools
      - lvm2

# Rook-Ceph wants rbd modules loaded
- name: Ensure rbd module loads
  community.general.modprobe:
    name: rbd
    state: present
    persistent: present

# Longhorn wants uio and nvme modules loaded
- name: Ensure uio module loads
  community.general.modprobe:
    name: uio
    state: present
    persistent: present
- name: Ensure uio_pci_generic module loads
  community.general.modprobe:
    name: uio_pci_generic
    state: present
    persistent: present
- name: Ensure nvme-tcp module loads
  community.general.modprobe:
    name: nvme-tcp
    state: present
    persistent: present

# Set hugepages for Longhorn
- ansible.posix.sysctl:
    name: vm.nr_hugepages
    value: "1024"
    state: present

# provision the extra longhorn disks
- name: Create a ext4 filesystem on /dev/vda
  community.general.filesystem:
    fstype: ext4
    dev: /dev/vda
    resizefs: true

- name: Mount up extra disk
  ansible.posix.mount:
    path: /var/lib/longhorn
    src: /dev/vda
    fstype: ext4
    state: mounted

- name: Creating a file with content
  copy:
    dest: "/etc/multipath.conf"
    content: |
      defaults {
          user_friendly_names yes
          find_multipaths yes
      }

## install apparmor profile for minio's directpv
- name: Download apparmor profile for directpv
  get_url:
    url: https://raw.githubusercontent.com/minio/directpv/v4.0.10/apparmor.profile
    dest: /etc/apparmor.d/directpv
    owner: root
    group: root
    mode: 0644

- name: Read device information
  community.general.parted:
    device: /dev/sda
    unit: MiB
  register: disk_info

- name: Resize the volume group to use all available space on /dev/sda{{ disk_info.partitions | length }}
  community.general.lvg:
    vg: ubuntu-vg
    pvs: /dev/sda{{ disk_info.partitions | length }}
    pvresize: yes

- name: Extend the logical volume to use all remaining space in the volume group
  community.general.lvol:
    vg: ubuntu-vg
    lv: ubuntu-lv
    size: +100%FREE

- name: Resize filesystem
  ansible.builtin.command: resize2fs /dev/ubuntu-vg/ubuntu-lv

# provision extra non-os disk space
- name: Create a ext4 filesystem on /dev/vdc
  community.general.filesystem:
    fstype: ext4
    dev: /dev/vdc
    resizefs: true

- name: Unmount wrong space
  ansible.posix.mount:
    path: /var/lib/vulfspace
    src: /dev/vdc
    fstype: ext4
    state: unmounted

- name: Mount up for default openebs
  ansible.posix.mount:
    path: /var/openebs/local
    src: /dev/vdc
    fstype: ext4
    state: mounted
