apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/creedasaurus/homelab
        revision: HEAD
        directories:
          - path: k8s/apps/*
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: homelab
      source:
        repoURL: https://github.com/creedasaurus/homelab
        targetRevision: HEAD
        path: '{{ path }}'
      destination:
        name: in-cluster
        namespace: '{{ path.basename }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
