apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- project.yml
- application-set.yml
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/managed-by: argocd
