apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert3
spec:
  secretName: example3-tls
  dnsNames:
    - "example3.local.vulf.haus"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
