apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: example3-
resources:
  - cm.yml
  - certificate.yml
  - deployment.yml
  - ingress.yml
  - svc.yml
labels:
  - includeSelectors: true
    pairs:
      app: example
