apiVersion: v1
kind: Secret
metadata:
  name: myminio-env-configuration
  namespace: vulfminio
stringData:
  config.env: |-
    export MINIO_ROOT_USER="minio"
    export MINIO_ROOT_PASSWORD="minio123"
type: Opaque
