existingSecret:
  name: minio-secret
tenant:
  name: vulfminio
  configuration:
    name: minio-secret
  features:
    bucketDNS: true
    domains:
      minio:
        - https://s3.vulf.haus
      console: https://minio.vulf.haus
    enableSFTP: false
  certificate:
    requestAutoCert: false

  pools:
    - servers: 4
      name: vulf-pool-0
      volumesPerServer: 2
      size: 32Gi
      storageClassName: directpv-min-io

  buckets:
    - cloudnative-pg
