name: kargo-render-by-me
description: Publish rendered manifests to an environment branch
inputs:
  personalAccessToken:
    description: A personal access token that allows Kargo Render to write to your repository
    required: true
  targetBranch:
    description: The environment branch for which you want to render manifests
    required: true
  allowEmpty:
    description: Whether to allow rendered manifests to be empty. If false this is disallowed as a safeguard against scenarios where a bug of any kind might otherwise cause Kargo Render to wipe out the contents of the target branch in error.
    required: false
    default: 'false'
runs:
  using: docker
  image: docker://ghcr.io/akuity/kargo-render:v0.1.0-rc.42
  args: ["action"]
