---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  target:
    name: authentik-secret
    template:
      engineVersion: v2
      data:
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        AUTHENTIK_POSTGRESQL__HOST: postgres17-rw.database.svc.cluster.local
        AUTHENTIK_POSTGRESQL__NAME: &table authentik
        AUTHENTIK_POSTGRESQL__USER: *table
        AUTHENTIK_POSTGRESQL__PASSWORD: "{{ .AUTHENTIK_POSTGRES_PASS }}"
        AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__HOST: postgres17-ro.database.svc.cluster.local
        AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__NAME: *table
        AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__USER: *table
        AUTHENTIK_POSTGRESQL__READ_REPLICAS__0__PASSWORD: "{{ .AUTHENTIK_POSTGRES_PASS }}"
        INIT_POSTGRES_DBNAME: authentik
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .AUTHENTIK_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .AUTHENTIK_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: cloudnative-pg
