global:
  storageClass: local-path
  envFrom:
    - secretRef:
        name: authentik-secret

authentik:
  log_level: debug

server:
  ingress:
    enabled: true
    ingressClassName: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    hosts:
      - authentik.vulf.haus
    tls:
      - secretName: cm-shared-wildcard-vulfhaus-tls
  initContainers:
    init-db:
      image: ghcr.io/onedr0p/postgres-init:16.3
      envFrom:
        - secretRef:
            name: authentik-secret

worker:
  initContainers:
    init-db:
      image: ghcr.io/onedr0p/postgres-init:16.3
      envFrom:
        - secretRef:
            name: authentik-secret
redis:
  enabled: true
