apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

resources:
  - ns.yml
  - ingress.yml

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 28.3.0
    releaseName: traefik
    namespace: traefik
    includeCRDs: true
    valuesFile: values.yml
