globalArguments:
  - "--global.checknewversion=false"
  - "--global.sendanonymoususage=false"
ports:
  websecure:
    tls:
      enabled: true
ingressRoute:
  dashboard:
    enabled: false
providers:
  kubernetesCRD:
    enabled: true
    ingressClass: "traefik-external"
    allowCrossNamespace: true
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: true
rbac:
  enabled: true
service:
  enabled: true
  spec:
    loadBalancerIP: 192.168.66.100
