apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: apps
  source:
    repoURL: "https://github.com/creedasaurus/homelab.git"
    path: apps/services/database/postgres
    targetRevision: main
  destination:
    namespace: database
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
