apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vulfminio
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: apps
  destination:
    namespace: vulfminio
    name: in-cluster
  sources:
    - repoURL: "https://github.com/creedasaurus/homelab.git"
      targetRevision: main
      path: apps/services/vulfminio
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
