apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openebs

resources:
  - ns.yaml

helmCharts:
  - name: openebs
    repo: https://openebs.github.io/openebs
    version: "4.1.1"
    releaseName: openebs
    namespace: openebs
    includeCRDs: true
    valuesFile: values.yaml
