apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio-operator

helmCharts:
  - name: operator
    repo: https://operator.min.io
    version: "6.0.4"
    releaseName: operator
    namespace: minio-operator
    includeCRDs: true
    valuesFile: values.yml
