console:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    host: minio-console.vulf.haus
    tls:
      - secretName: cm-shared-wildcard-vulfhaus-tls
