apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homelab-deux-repo
  namespace: argocd
spec:
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  target:
    name: homelab-deux-repo
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: https://github.com/creedasaurus/homelab-deux.git
        username: creedasaurus
        password: >-
          {{ printf "{{ .access-token | toString }}" }}
  data:
    - secretKey: access-token
      remoteRef:
        key: github-read-access
        property: github-read-access-token
