apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homelab-deux-repo
  namespace: argocd
spec:
  data:
  - remoteRef:
      key: github
      property: read-access-token
    secretKey: accessToken
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-connect
  target:
    name: homelab-deux-repo
    template:
      data:
        password: '{{ .accessToken }}'
        type: git
        url: https://github.com/creedasaurus/homelab-deux.git
        username: creedasaurus
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
