apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: csi-driver-smb
    repo: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
    version: v1.14.0
    releaseName: csi-driver-smb
    namespace: kube-system

resources:
  - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/deploy/example/storageclass-smb.yaml
