---
k3s_cluster:
  children:
    server:
      hosts:
        192.168.66.21:
        192.168.66.22:
        192.168.66.23:
        192.168.66.24:
        192.168.66.25:
        192.168.66.26:
  vars:
    ansible_user: vulfadmin
    #     agent:
    #       hosts:
    #         192.16.35.12:
    #         192.16.35.13:
    #
  # Required Vars
  #
  # vars:
  #    ansible_port: 22
  #    ansible_user: debian
  #    k3s_version: v1.26.9+k3s1
  #    token: "mytoken"  # Use ansible vault if you want to keep it secret
  #    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
  #    extra_server_args: ""
  #    extra_agent_args: ""
  #
