apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: shared-wildcard-vulfhaus-cert
  namespace: cert-manager
spec:
  secretName: cm-shared-wildcard-vulfhaus-tls
  additionalOutputFormats:
    - type: CombinedPEM
    - type: DER
  dnsNames:
    - "vulf.haus"
    - "*.vulf.haus"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "media,authentik,traefik,argocd,development,longhorn-system,atuin,gluetun,minio-operator,vulfminio,database,immich,home,photos"
