apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-shared-cert
spec:
  secretName: test-shared-tls
  dnsNames:
    - "testshared.local.vulf.haus"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      # reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "media,longhorn-system"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "media,longhorn-system" # Control auto-reflection namespaces
