apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  data:
  - remoteRef:
      key: cloudflare-cert-api-token
      property: token
    secretKey: api-token
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password-connect
  target:
    creationPolicy: Owner
