apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: gabled.reaper-0k@icloud.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - selector:
          dnsZones:
            - "vulf.haus"
            - "local.vulf.haus"
        dns01:
          route53:
            region: us-east-1
            # The AWS access key ID can be specified using the literal accessKeyID parameter
            # or retrieved from a secret using the accessKeyIDSecretRef
            # If using accessKeyID, omit the accessKeyIDSecretRef parameter and vice-versa
            accessKeyIDSecretRef:
              key: keyid
              name: home-server-aws-token
            secretAccessKeySecretRef:
              key: accesskey
              name: home-server-aws-token
