apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-route53-access
spec:
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
    - secretKey: keyid
      remoteRef:
        key: aws-route53-access
        property: keyid
    - secretKey: accesskey
      remoteRef:
        key: aws-route53-access
        property: accesskey
