apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-route53-access
  namespace: cert-manager
spec:
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
    - secretKey: keyid
      remoteRef:
        key: aws-route53-access
        property: keyid
    - secretKey: accesskey
      remoteRef:
        key: aws-route53-access
        property: accesskey
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: cloudflare-cert-api-token
        property: token
