apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#namespace: cert-manager  # XXX: Do not set this - it will override roles for kube-system needed for leader election of cainjector

resources:
  - cluster-issuer-prod.yml
  - cluster-issuer-staging.yml
  - external-secrets-dns.yml
  - certificate.yml
  - staging-certificate.yml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.16.1
    releaseName: cert-manager
    namespace: cert-manager
    includeCRDs: true
    valuesFile: values.yml

# label app.kubernetes.io/instance=cert-manager causes warnings for all 6 Cert Manager CRDs in ArgoCD, eg:
#
#  SharedResourceWarning 	CustomResourceDefinition/certificaterequests.cert-manager.io is part of applications cert-manager-production and cert-manager
#
#   https://github.com/argoproj/argo-cd/issues/6728
#
patches:
  - path: ./remove-instance-label.jsonpatch.yml
    target:
      kind: CustomResourceDefinition
      labelSelector: app.kubernetes.io/instance=cert-manager
