apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: networking
  destination:
    namespace: traefik
    name: in-cluster
  source:
    repoURL: https://traefik.github.io/charts
    targetRevision: v26.1.0
    chart: traefik
    helm:
      valuesObject:
        globalArguments:
          - "--global.checknewversion=false"
          - "--global.sendanonymoususage=false"
        ports:
          # web:
          #   redirectTo:
          #     port: websecure
          websecure:
            tls:
              enabled: true
        ingressRoute:
          dashboard:
            enabled: false
        providers:
          kubernetesCRD:
            enabled: true
            ingressClass: "traefik-external"
            allowCrossNamespace: true
          kubernetesIngress:
            enabled: true
            publishedService:
              enabled: true
        rbac:
          enabled: true
        service:
          enabled: true
          spec:
            loadBalancerIP: 192.168.25.52

  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
