apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: networking
  destination:
    namespace: traefik
    name: in-cluster
  sources:
    - repoURL: https://traefik.github.io/charts
      targetRevision: v28.0.0
      chart: traefik
      helm:
        values: |
          globalArguments:
            - "--global.checknewversion=false"
            - "--global.sendanonymoususage=false"
          ports:
            websecure:
              tls:
                enabled: true
          ingressRoute:
            dashboard:
              enabled: false
          providers:
            kubernetesCRD:
              enabled: true
              ingressClass: "traefik-external"
              allowCrossNamespace: true
            kubernetesIngress:
              enabled: true
              publishedService:
                enabled: true
          rbac:
            enabled: true
          service:
            enabled: true
            spec:
              loadBalancerIP: 192.168.66.100
    - repoURL: "https://github.com/creedasaurus/homelab.git"
      targetRevision: main
      path: apps/networking/traefik
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
