apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: networking
  destination:
    namespace: traefik
    name: in-cluster
  sources:
    - repoURL: "https://github.com/creedasaurus/homelab.git"
      targetRevision: main
      path: apps/networking/traefik
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
