kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"
  dataLocality: best-effort
  diskSelector: "fast"
  nodeSelector: "mega"
