apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
  namespace: longhorn-system
  annotations:
    kubernetes.io/ingress.class: traefik-external

spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.vulf.haus`)
      kind: Rule
      middlewares:
        - name: longhorn-frontend-basicauth
          namespace: longhorn-system
      services:
        - name: longhorn-frontend
          port: 80
  tls:
    # shared wildcard cert for *.vulf.haus
    secretName: cm-shared-wildcard-vulfhaus-tls
