kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: large
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"
  diskSelector: "large"
  nfsOptions: "vers=4.2,noresvport,softerr,timeo=600,retrans=5"
