kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: large
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "1"
  dataLocality: best-effort
  diskSelector: "large"
  nodeSelector: "mega"
