apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-pg
spec:
  instances: 3

  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-pg-user-creds

  storage:
    storageClass: local-path
    size: 1Gi
  superuserSecret:
    name: authentik-pg-superuser-creds
  enableSuperuserAccess: true

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  monitoring:
    enablePodMonitor: false

  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      data:
        compression: bzip2
      wal:
        compression: bzip2
        maxParallel: 8
      destinationPath: s3://cloudnative-pg/
      endpointURL: https://s3.vulf.haus
      # Note: serverName version needs to be incremented
      # when recovering from an existing cnpg cluster
      serverName: &currentCluster authentik-pg-v1
      s3Credentials:
        accessKeyId:
          name: authentik-pg-backup-creds
          key: aws-access-key-id
        secretAccessKey:
          name: authentik-pg-backup-creds
          key: aws-secret-access-key
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authentik-pg
spec:
  schedule: "0 0 0 * * *"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: authentik-pg
