apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-pg-user-creds
spec:
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: authentik
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: authentik-creds
        property: authentik-user-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-pg-superuser-creds
spec:
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  target:
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: postgres
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: authentik-creds
        property: authentik-superuser-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-secret-key
spec:
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  data:
    - secretKey: key
      remoteRef:
        key: authentik-creds
        property: authentik-secret-key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik-pg-backup-creds
spec:
  secretStoreRef:
    name: 1password-connect
    kind: ClusterSecretStore
  target:
    name: authentik-pg-backup-creds
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: aws-access-key-id
      remoteRef:
        key: cloudnative-pg
        property: backup-bucket-access-key

    - secretKey: aws-secret-access-key
      remoteRef:
        key: cloudnative-pg
        property: backup-bucket-secret-key
