global:
  env:
    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-secret-key
          key: key
    - name: AUTHENTIK_POSTGRESQL__HOST
      value: authentik-pg-rw
    - name: AUTHENTIK_POSTGRESQL__NAME
      value: authentik
    - name: AUTHENTIK_POSTGRESQL__USER
      value: authentik
    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-pg-user-creds
          key: password

authentik:
  log_level: debug

server:
  ingress:
    enabled: true
    ingressClassName: "traefik"
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    hosts:
      - authentik.vulf.haus
    tls:
      - secretName: cm-shared-wildcard-vulfhaus-tls

redis:
  enabled: true
  storageClass: "local-path"
