apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: 1password-connect
  namespace: external-secrets
spec:
  conditions:
  - namespaces:
    - authentik
    - media
    - cert-manager
    - argocd
    - default
    - development
    - atuin
    - minio-operator
    - gluetun
    - vulfminio
    - database
    - immich
    - home
    - photos
  provider:
    onepassword:
      auth:
        secretRef:
          connectTokenSecretRef:
            key: token
            name: 1password-connect-token
            namespace: external-secrets
      connectHost: http://onepassword-connect.op-connect:8080
      vaults:
        homelab: 1
