apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: 1password-connect
  namespace: external-secrets
spec:
  provider:
    onepassword:
      # this is installed with bootstrap stuff as it requires a manual secret
      connectHost: http://onepassword-connect.op-connect:8080
      vaults:
        homelab: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            namespace: external-secrets
            # also referred to in the bootstrap step
            name: 1password-connect-token
            key: token
  conditions:
    - namespaces:
        - media
        - cert-manager
