apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: example-secret-store
spec:
  # provider field contains the configuration to access the provider
  # which contains the secret exactly one provider must be configured.
  provider:
    fake:
      data:
        - key: "/foo/bar"
          value: "HELLO1"
          version: "v1"
        - key: "/foo/bar"
          value: "HELLO2"
          version: "v2"
        - key: "/foo/baz"
          value: '{"john": "doe"}'
          version: "v1"
  # Conditions about namespaces in which the ClusterSecretStore is usable for ExternalSecrets
  conditions:
    - namespaces:
        - "media"
