apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-secrets-webhook
    app.kubernetes.io/version: v0.10.5
    helm.sh/chart: external-secrets-0.10.5
  name: external-secrets-webhook
  namespace: external-secrets
